fix(PetitioResponse): fixed that non-alphabetic letters was being broken
helperdiscord/centra pull request #11
Opened 2021-04-01 21:24 UTC by zero734kr

Closes #10 

Using Buffer#toString fixed this because it parses string to utf-8 automatically.

2021-04-01 21:27 UTC, zero734kr commented
Ah, no problem if you prefer to delete the ``tests/checkKorean.test.ts`` file because I used it only to test if it was really working

2021-04-01 21:38 UTC, tbnritzdoge requested changes
Once the Korean Tests are removed this looks good to merge although we may want to incorporate a encoding type in buffer#toString like in PetitioResponse#text. I will invoke @Nytelife26 to see his opinion on that. Thanks for the PR :)

2021-04-01 21:38 UTC, tbnritzdoge requested changes
Once the Korean Tests are removed this looks good to merge although we may want to incorporate a encoding type in buffer#toString like in PetitioResponse#text. I will invoke @Nytelife26 to see his opinion on that. Thanks for the PR :)

2021-04-01 21:39 UTC, tbnritzdoge requested changes
Once the Korean Tests are removed this looks good to merge although we may want to incorporate a encoding type in buffer#toString like in PetitioResponse#text. I will invoke @Nytelife26 to see his opinion on that. Thanks for the PR :)

2021-04-01 21:39 UTC, tbnritzdoge commented
Apologies for spamming this, my internet was having issues.

2021-04-01 21:45 UTC, zero734kr commented
@tbnritzdoge applied change requests as you requested 👍

2021-04-01 21:51 UTC, tbnritzdoge requested changes

2021-04-01 21:51 UTC, tbnritzdoge commented on src/lib/PetitioResponse.ts
> +         * @param {BufferEncoding} [encoding="utf8"] The encoding to use before parsing to json.
formatting

2021-04-02 17:13 UTC, Nytelife26 commented
The reason we didn't use `toString` or the like it is because it is approximately 3x slower according to our testing. I will look into ways to rectify this now, perhaps if there is a way to use `fromCharCode` with string encoding. Thank you for the PR!

2021-04-02 17:21 UTC, Nytelife26 commented on src/lib/PetitioResponse.ts
> +         * @param {BufferEncoding} [encoding="utf8"] The encoding to use before formatting to json.
Why was the whitespace on this line changed?

2021-04-02 17:48 UTC, Nytelife26 commented
Nevermind, looks good to me. Ready to merge once CI passes.

2021-04-02 17:53 UTC, merged