Add "HEAD" method
helperdiscord/centra pull request #17
Opened 2021-04-08 08:45 UTC by HeadTriXz

2021-04-08 11:59 UTC, tbnritzdoge approved these changes
lgtm

2021-04-09 03:03 UTC, Nytelife26 requested changes
Many thanks for the PR! I think while we're at it, we might as well add all the other request methods from HTTP/1.0 and HTTP/1.1 too, so if you can commit these we're good to go :)

2021-04-09 03:03 UTC, Nytelife26 commented on src/lib/PetitioRequest.ts
> +export type HTTPMethod = "GET" | "HEAD" | "POST" | "PATCH" | "DELETE" | "PUT";
```suggestion
export type HTTPMethod = "GET" | "HEAD" | "POST" | "OPTIONS" | "PUT" | "DELETE" | "TRACE" | "CONNECT" | "PATCH";
```

2021-04-09 11:13 UTC, tbnritzdoge approved these changes

2021-04-09 14:50 UTC, Vetlix approved these changes
LGTM

2021-04-09 15:00 UTC, Nytelife26 approved these changes
Thank you. Merging now :)

2021-04-09 15:00 UTC, merged