chore: export HTTPMethod
helperdiscord/centra pull request #32
Opened 2021-05-22 03:37 UTC by tbnritzdoge

export the http method

2021-05-22 11:31 UTC, Nytelife26 requested changes
Doesn't the second export break things, since the first declared that its only export should be the function? Also, make `ts-ignore` usage more clear.

2021-05-22 13:52 UTC, tbnritzdoge commented
> Doesn't the second export break things, since the first declared that its only export should be the function? Also, make `ts-ignore` usage more clear.

I tested and someone it doesn't. All it seems to do is tell ts that you can import the type from root rather than from the explicit type path (dist/lib/PetitioRequest iirc)

2021-05-31 01:27 UTC, Nytelife26 requested changes

2021-05-31 01:27 UTC, Nytelife26 commented on src/index.ts
> +// @ts-ignore Typescript is wrong
This needs to be more descriptive as to why it is required.

2021-10-03 21:17 UTC, merged